from flask import Flask, render_template, request, redirect, url_for, session, send_file
from flask_sqlalchemy import SQLAlchemy
import os
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

app = Flask(__name__)
app.secret_key = "secret"

# DATABASE FIX (important)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///scans.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)

# ---------------- MODELS ---------------- #

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50))
    password = db.Column(db.String(50))


class Scan(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    target = db.Column(db.String(100))
    open_ports = db.Column(db.Text)
    filtered_ports = db.Column(db.Text)
    subdomains = db.Column(db.Text)
    nikto = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

# ---------------- INIT DB ---------------- #

with app.app_context():
    db.create_all()

    # Create default admin if not exists
    if not User.query.filter_by(username="admin").first():
        db.session.add(User(username="admin", password="admin"))
        db.session.commit()

# ---------------- ROUTES ---------------- #

@app.route("/", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        user = User.query.filter_by(username=username, password=password).first()

        if user:
            session["user"] = username
            return redirect("/scan")
        else:
            return "Invalid credentials"

    return render_template("login.html")


@app.route("/scan", methods=["GET", "POST"])
def scan():
    if "user" not in session:
        return redirect("/")

    if request.method == "POST":
        target = request.form["target"]

        # ----------- FAKE SCAN DATA (Replace with real tools later) ----------- #
        open_ports = [
            "80/tcp (http) - Low",
            "443/tcp (https) - Medium",
            "22/tcp (ssh) - High"
        ]

        filtered_ports = ["21/tcp", "25/tcp"]
        subdomains = ["dev."+target, "test."+target]

        nikto = "Nikto scan result example...\nVulnerability found..."

        # ----------- SAVE TO DB ----------- #
        scan = Scan(
            target=target,
            open_ports="\n".join(open_ports),
            filtered_ports="\n".join(filtered_ports),
            subdomains="\n".join(subdomains),
            nikto=nikto
        )

        db.session.add(scan)
        db.session.commit()

        # ----------- COUNT SEVERITY ----------- #
        low_count = sum(1 for p in open_ports if "Low" in p)
        medium_count = sum(1 for p in open_ports if "Medium" in p)
        high_count = sum(1 for p in open_ports if "High" in p)

        return render_template(
            "result.html",
            target=target,
            open_ports=open_ports,
            filtered_ports=filtered_ports,
            subdomains=subdomains,
            nikto=nikto,
            low_count=low_count,
            medium_count=medium_count,
            high_count=high_count
        )

    return render_template("scan.html")


@app.route("/download_pdf")
def download_pdf():
    target = request.args.get("target")

    file_path = f"report_{target}.pdf"

    doc = SimpleDocTemplate(file_path)
    styles = getSampleStyleSheet()

    content = []
    content.append(Paragraph(f"Scan Report for {target}", styles["Title"]))
    content.append(Spacer(1, 10))
    content.append(Paragraph("Generated by AutoVulnScanner", styles["Normal"]))

    doc.build(content)

    return send_file(file_path, as_attachment=True)


@app.route("/logout")
def logout():
    session.pop("user", None)
    return redirect("/")


if __name__ == "__main__":
    app.run(debug=True)